[project]
name = "ai-nutrition-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python-headless>=4.12.0.88",
    "pandas>=2.3.3",
    "streamlit>=1.52.2",
    "ultralytics>=8.3.252",
]
